image: docker:20.10.7

options:
  size: 2x

pipelines:
  default:
    - step:
        name: Build and Deploy Node App
        image: docker:20.10.7
        services:
          - docker
        script:
          - echo "🔧 Setting up Docker Compose for CI/CD"

          # Install docker-compose manually (Bitbucket doesn't include it by default)
          - apk add --no-cache curl py3-pip
          - pip install docker-compose

          # Print Docker and Compose versions
          - docker -v
          - docker-compose -v

          # Build Docker containers
          - docker-compose -f docker-compose.yml build

          # Optionally run the services
          - docker-compose -f docker-compose.yml up -d

          # List containers
          - docker ps

definitions:
  services:
    docker:
      memory: 2048
