image: atlassian/default-image:latest  # Official Bitbucket CI image with Docker support

pipelines:
  default:
    - step:
        name: Build and Run Docker App
        services:
          - docker
        caches:
          - docker
        size: 2x
        script:
          - echo "Starting CI build..."

          # Install Docker Compose manually (not included by default)
          - apk add --no-cache docker-compose

          # Build containers
          - docker-compose -f docker-compose.yml build

          # Optionally bring up the stack to verify
          - docker-compose -f docker-compose.yml up -d

          # Show running containers
          - docker ps

          - echo "Build completed successfully."
