image: atlassian/default-image:3

definitions:
  services:
    docker:
      memory: 2048

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        caches:
          - node
        script:
          - docker-compose build
          - docker-compose up -d
          - sleep 10  # Give some time for services to start
          - docker-compose exec -T node-app npm test
          - docker-compose down
          