image: docker/compose:1.29.2

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        script:
          # Create .env file using repository variables
          - touch .env
          - echo "PORT=$PORT" >> .env
          - echo "MONGO_USER=$MONGO_USER" >> .env
          - echo "MONGO_PASSWORD=$MONGO_PASSWORD" >> .env
          - echo "MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME" >> .env
          - echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >> .env
          
          # Create a docker-compose.override.yml file to modify the volume configuration for CI
          - |
            cat > docker-compose.override.yml << EOF
            version: "3"
            services:
              mongo:
                volumes:
                  - ./mongo-data:/data/db
            volumes:
              mongo-db:
                driver: local
            EOF
          
          # Make the directory for mongo data
          - mkdir -p mongo-data
          
          # Build and run the application
          - docker-compose build
          - docker-compose up -d
          
          # Verify services are running
          - docker-compose ps
          
          # Cleanup
          - docker-compose down

          # Authenticate and push the image to Docker Hub
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker push $DOCKER_USERNAME/node_app

services:
  docker:
    memory: 2048