image: docker/compose:1.29.2  # Includes both Docker + Compose

pipelines:
  default:
    - step:
        name: Build and Run App
        services:
          - docker
        size: 2x  # Gives extra memory/CPU (optional)
        caches:
          - docker
        script:
          - echo "Starting Build Process..."
          
          # Show working directory and files
          - pwd
          - ls -la

          # Build Docker images using docker-compose
          - docker-compose -f docker-compose.yml build

          # (Optional) Spin up containers for testing
          - docker-compose -f docker-compose.yml up -d

          # Wait a few seconds for services to start
          - sleep 10

          # Show running containers
          - docker ps

          # Done!
          - echo "✅ Pipeline complete!"
