image: docker/compose:1.29.2

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        script:
          # Create .env file using repository variables
          - touch .env
          - echo "PORT=$PORT" >> .env
          - echo "MONGO_USER=$MONGO_USER" >> .env
          - echo "MONGO_PASSWORD=$MONGO_PASSWORD" >> .env
          - echo "MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME" >> .env
          - echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >> .env
          
          # Build and run the application
          - docker-compose build
          - docker-compose up -d
          
          # Verify services are running
          - docker-compose ps
          
          # Cleanup
          - docker-compose down

services:
  docker:
    memory: 2048
