image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Build and Run Docker Compose
        services:
          - docker
        caches:
          - docker
        script:
          - echo "Starting CI/CD pipeline..."

          # Print Docker version
          - docker --version

          # Install Docker Compose
          - echo "Installing Docker Compose..."
          - apt-get update && apt-get install -y curl
          - curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - chmod +x /usr/local/bin/docker-compose
          - docker-compose --version

          # Build and run containers
          - docker-compose -f docker-compose.yml build
          - docker-compose -f docker-compose.yml up -d

          # Show running containers
          - docker ps
