image: atlassian/default-image:latest

options:
  size: 2x  # Gives extra memory and CPU for builds

pipelines:
  default:
    - step:
        name: Build and Run Docker Compose App
        services:
          - docker
        caches:
          - docker
        script:
          - echo "Installing Docker Compose..."
          - apk add --no-cache docker-compose

          - echo "Building Docker containers..."
          - docker-compose -f docker-compose.yml build

          - echo "Starting containers in background..."
          - docker-compose -f docker-compose.yml up -d

          - echo "Showing running containers..."
          - docker ps

          # Optional: wait for app to boot
          - sleep 10

          # Optional: check logs
          - docker-compose logs --tail=50
