version : "3" 
services: 
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    # ports:
    #   - "3000:3000"
    image: cjankawan/node_app
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev # overwrite >>> CMD ["node", "index.js"] <<<
    depends_on:
      - mongo

  mongo:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=mongo_username
    #   - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    env_file:
      - .env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
