version : "3" 
services: 
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGO_USER=mongo_username
      - MONGO_PASSWORD=mongo_password
    # env_file:
    #   - ./.env
    command: npm run dev # overwrite >>> CMD ["node", "index.js"] <<<
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_username
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    # env_file:
    #   - ./.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
